Message:
    Help:
        commands:
            - " "
            - "&6&l| КОМАНДЫ ДЛЯ ИГРОКОВ | "
            - " "
            - "&a[>>] &f/quest <message> (Подать вопрос хелперам) "
            - "&a[>>] &f/honline (Показывает кол-во хелперов онлайн) "
            - " "
            - "&c&l| КОМАНДЫ ДЛЯ ХЕЛПЕРОВ/АДМИНИСТРАТОРОВ | "
            - " "
            - "&a[>>] &f/ans <player> <message> (Отправить ответ игроку)"
            - "&a[>>] &f/hlist <player> <add/remove> <reason> (Добавить/Удалить игрока из чс хелперов)"
            - "&a[>>] &f/hcheck <player> <your_nick> (Показывает статистику хелпера)"
            - "&a[>>] &f/achat <message> (Отправить сообщение в чат хелперов)"
            - "&a[>>] &f/hmute <player> <second> <reason> (Замутить игрока на время)"
            - "&a[>>] &f/hset <name> <give/take> (Выдать/Забрать хелперку)"
            - "&a[>>] &f/hwarn <player> <value_warn> (Выдать warn хелперу)"
            - "&a[>>] &f/hunmute <player> (Снять мут с хелпера)"
#=========#===========#
    Question:
        Muted: "&c&l[ОШИБКА] &fВы не можете подавать вопросы, так как получили временную блокировку! "
        Format: "&6&l[НОВЫЙ ВОПРОС] &fВопрос:&e %question%&8&l|| &fОтправитель: &n%player%&f "
        PlayerHaveQuestion: "&9&l[ОПОВЕЩЕНИЕ] &fВы уже имеете &cактивный&f вопрос!"
        PlayerNotHaveQuestion: "&c&l[ОШИБКА] &fИгрок &6%player% &fне имеет вопроса!"
        QuestionNull: "&e&l[ПРЕДУПРЕЖДЕНИЕ] &fВопрос не может быть пустым!"
        CooldownTimeOver: "&9&l[ОПОВЕЩЕНИЕ] &fСистема автоматически &cотклонила&f ваш вопрос, так как никто на него не ответил!"
#=========#===========#
    Helper:
        Status:
            JoinHelper: " &c&l>> &fХелпер &6%player% &fзашел и готов &cотвечать&f на ваши вопросы!"
            LeaveHelper: "&c&l>> &fХелпер &6%player% &fпокинул сервер!"
        Chat:
            Format: "&c&l[ХЕЛПЕРЫ] &f%sender_name% &7->&e %message%"
        Rank:
            SetHelper: "&9&l[ОПОВЕЩЕНИЕ] &fВы успешно &c%value% &fправа хелпера игроку &6%player%"
            PlayerSetHelper: "&9&l[ОПОВЕЩЕНИЕ] &fВам успешно &c%value% &fправа хелпера"
        Mute:
            UnMutePlayer: "&9&l[ОПОВЕЩЕНИЕ] &fВы &cсняли&f мут с игрока &6%player%"
            UnMute: "&9&l[ОПОВЕЩЕНИЕ] &fАдминистратор &6%player%&f снял с вас мут"
            PlayerNotMuted: "&c&l[ОШИБКА] &fИгрок &6%player% &c&nне имеет&f активного мута!"
            PlayerHaveMute: "&c&l[ОШИБКА] &fИгрок &6%player%&c уже &c&nимеет&f активный мут!"
            PlayerAddMute: "&9&l[ОПОВЕЩЕНИЕ] &fВы успешно &4замутили&f игрока &6%player%&f на &e&n%time%&e cекунд(-ы)"
            AutoTakeOffMute: "&9&l[ОПОВЕЩЕНИЕ] &fВремя мута истекло! Вы можете &aподавать&f вопросы"
            PlayerMute: "&9&l[ОПОВЕЩЕНИЕ] &fВас &cзамутил&f хелпер &6%player% &fна &e&n%time%&e секунд(-ы)&f по причине: %reason%"
        Warns:
            PlayerSetWarn: "&9&l[ОПОВЕЩЕНИЕ] &fАдминистратор &6%player% &fвыдал вам варн(-ы) &c(%value_warn%/%max_warn%)"
            SetWarn: "&9&l[ОПОВЕЩЕНИЕ] &fВы выдали хелперу &6%player%&f варны в количестве &c(%warn%)"
        #
        HelpersNull: "&c&l[ОШИБКА] &fНа данный момент на сервере нет активных хелперов!"
        MessageEmpty: "&e&l[ПРЕДУПРЕЖДЕНИЕ] &fВаше сообщение не может быть пустым"
        ShortMessage: "&e&l[ПРЕДУПРЕЖДЕНИЕ] &fВаше сообщение/причина/вопрос короче минимального значения &c%min_size%"
        NotHelper: "&c&l[ОШИБКА] &fВы не являетесь хелпером!"
#=========#===========#
    BlackList:
        PlayerInBlackList: "&c&l[ОШИБКА] &fИгрок &6%player% &fуже находится в черном списке хелперов!"
        PlayerNotBlackList: "&c&l[ОШИБКА] &fИгрок &6%player%&f не найден в черном списке хелперов!"
        InfoPlayerAddBlacklist: "&9&l[ОПОВЕЩЕНИЕ] &fАдминистратор &6%player%&f добавил вас в ЧС хелперов по причине: %reason%"
        InfoPlayerRemoveBlacklist: "&9&l[ОПОВЕЩЕНИЕ] &fАдминистратор &6%player% &fудалил вас из ЧС хелперов!"
        AddBlacklistPlayer: "&9&l[ОПОВЕЩЕНИЕ] &fВы добавили игрока &6%player%&f в ЧС хелперов по причине: &f%reason%"
        RemoveBlacklistPlayer: "&9&l[ОПОВЕЩЕНИЕ] &fВы удалили игрока &6%player% &fиз ЧС хелперов!"
#=========#===========#
    PlayerIsEmpty: "&c&l[ОШИБКА] &fИгрока &6%player% &fнет на сервере!"
    NotHavePermission: "&c&l[ОШИБКА] &fУ вас нет прав для данного действия!"
#=========#===========#
Settings:
    Global:
        SendStatusHelper: true # Отсылать сообщение о входе и выходе хелпера с сервера
        DenyWords:
            - Сука
            - Пизда
            - Залупа
            - Член
            - Писька
            - Сервер
            - Айпи
            - Хуйня
            - Параша
            - Уебан
            - Пидарас
            - Сучка
            - Еблан
            - .|.
            - Поебота
            - Лох
            - Соси
    Helper:
        MinSizeMessage: 1
        MaxWarn: 3
#
    MuteQuestion:
        MinSizeReason: 5
#
    Question:
        AutoClosingQuestion: 120 # Автоматическое отклонение вопроса, если в течении N секунд не было ответа
        MinSizeMessage: 5